# Generated by Django 5.1.7 on 2025-04-06 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingoffer',
            name='casting_director',
        ),
        migrations.AlterField(
            model_name='application',
            name='model_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='casting.modelprofile'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DirectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('agency_name', models.CharField(blank=True, help_text='Nazwa agencji', max_length=200)),
                ('agency_address', models.CharField(blank=True, help_text='Adres siedziby agencji', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='directors/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='castingoffer',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casting_offers', to='casting.directorprofile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
