# Generated by Django 5.1.7 on 2025-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0003_remove_castingoffer_casting_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='directorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
