# Generated by Django 5.1.7 on 2025-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0004_directorprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='castingoffer',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='agency_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='directorprofile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
