# Generated by Django 5.1.7 on 2025-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0005_alter_application_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='W cm', null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='measurements',
            field=models.CharField(blank=True, help_text='Np. 90-60-90', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='W kg', null=True),
        ),
    ]
