# Generated by Django 4.2.23 on 2025-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_savedbouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedbouquet',
            name='name',
            field=models.CharField(default='Bez nazwy', max_length=100),
            preserve_default=False,
        ),
    ]
